### ISSUE TITLE
GitHub Actions - reduce Matrix

### ISSUE THREAD

**Issue by greywidget** [greywidget/cov-badge-ned#4]
Given I'm on the free tier and it is just a test app - consider cutting down the matrix in `tests.yaml`:

```
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
```

Two os versions and two python versions is more than sufficient
